# Generated by Django 5.1.4 on 2025-01-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transferdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ssn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
