# Generated by Django 5.1.4 on 2025-01-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_address_transferdetails_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferdetails',
            options={'verbose_name': 'Transfer Details', 'verbose_name_plural': 'Transfer Details'},
        ),
        migrations.RemoveField(
            model_name='transferdetails',
            name='beneficiary_name',
        ),
    ]
