# Generated by Django 5.1.4 on 2025-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_transferdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_submitted_kyc',
            field=models.BooleanField(default=True, verbose_name='User has submitted verification for KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_verified_kyc',
            field=models.BooleanField(default=True, help_text='Tick if user has undergone KYC Verification and has been approved.', verbose_name='User is verified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_password_in_plaintext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
