# Generated by Django 5.1.4 on 2025-01-10 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_has_submitted_kyc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_dependents', models.IntegerField(default=0)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship_status', models.CharField(blank=True, max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_identity_number', models.CharField(blank=True, max_length=100, null=True)),
                ('government_id_type', models.CharField(blank=True, max_length=100, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_of_employment', models.FileField(blank=True, null=True, upload_to='identity/proof')),
                ('proof_of_income', models.FileField(blank=True, null=True, upload_to='identity/proof')),
                ('front_id_image', models.FileField(blank=True, null=True, upload_to='identity/proof')),
                ('back_id_image', models.FileField(blank=True, null=True, upload_to='identity/proof')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
