# Generated by Django 5.1.4 on 2025-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='marital_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
