# Generated by Django 5.1.4 on 2025-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_kyc_marital_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_submitted_kyc',
            field=models.BooleanField(default=False, verbose_name='User has submitted verification for KYC'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_verified_kyc',
            field=models.BooleanField(default=False, help_text='Tick if user has undergone KYC Verification and has been approved.', verbose_name='User is verified'),
        ),
    ]
