# Generated by Django 5.1.4 on 2025-01-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customuser_has_submitted_kyc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'verbose_name': 'KYC', 'verbose_name_plural': 'KYC'},
        ),
    ]
